name: Docker
on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"
jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.0.0
        with:
          dockerfile: Dockerfile
  build-image:
    runs-on: ubuntu-latest
    needs:
      - hadolint
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        id: setup-qemu
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: setup-docker
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: docker-meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/s-thom/paste
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Login to GitHub Container Registry
        id: docker-login-ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker-buildx
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy-to-fly:
    runs-on: ubuntu-latest
    needs:
      - hadolint
    # only build/deploy main branch on pushes
    if: ${{ (github.ref == 'refs/heads/main') && github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
